names:
  0: cracker_box
  1: sugar_box
  2: mustard_bottle
  3: chips_can
  4: tomato_soup_can
  5: windex_bottle
  6: bleach_cleanser
  7: apple
  8: banana
  9: tuna_fish_can
  10: potted_meat_can
  11: gelatin_box
  12: pudding_box
  13: master_chef_can
